import SubList from "@/components/SubList";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: 'INSIGHTS | Assinantes',
    description: 'Generated by create next app',
}

export default function Subscribers() {
    return (
        <SubList />
    )
}