import { Metadata } from "next"

export const metadata: Metadata = {
    title: 'INSIGHTS | Sobre',
    description: 'Generated by create next app',
}

export default function About() {
    return (
        <main className="flex flex-col gap-10 flex-1 justify-center px-10 lg:px-52 text-white">
            <h1 className="text-xl lg:text-2xl font-bold">Sobre a Newsletter &quot;Front-End Insights&quot;</h1>
            <div className="flex flex-col gap-2">
                <h1 className="text-lg font-bold">O que é a Front-End Insights?</h1>
                <p className="ps-16 text-sm md:text-base">Bem-vindo ao Insights! Somos apaixonados pelo mundo do desenvolvimento Frontend Web e estamos aqui para fornecer a você as informações mais valiosas, atualizações e recursos para aprimorar suas habilidades.</p>
            </div>
            <div className="flex flex-col gap-2">
                <h1 className="text-lg font-bold">Por que assinar a Front-End Insights?</h1>
                <p className="ps-16 text-sm md:text-base">Nosso objetivo é ajudar desenvolvedores Frontend a se manterem atualizados com as últimas tendências, técnicas e melhores práticas. Queremos ser o seu guia confiável no vasto universo do Frontend, oferecendo conteúdo de qualidade e insights práticos.</p>
            </div>
            <div>
                <h1 className="text-lg font-bold">O que Oferecemos?</h1>
                <ul className="list-decimal flex flex-col gap-2 p-2">
                    <li className="ms-16 font-light">
                        <span className="font-semibold text-md">Atualizações Semanais: </span>
                        <p className="text-sm md:text-base">Enviamos newsletters semanais diretamente para a sua caixa de entrada, repletas de artigos informativos, tutoriais, notícias e dicas úteis.</p>
                    </li>
                    <li className="ms-16 font-light">
                        <span className="font-semibold text-md">Comunidade Engajada: </span>
                        <p className="text-sm md:text-base">Fazemos parte de uma comunidade vibrante de desenvolvedores que compartilham conhecimento e experiências. Junte-se a nós nas redes sociais e fóruns para se conectar com outros entusiastas do Frontend.</p>
                    </li>
                    <li className="ms-16 font-light">
                        <span className="font-semibold text-md">Recursos de Aprendizado: </span>
                        <p className="text-sm md:text-base">Explore nossa crescente biblioteca de recursos, incluindo guias detalhados, cursos online recomendados e ferramentas úteis para aprimorar suas habilidades.</p>
                    </li>
                </ul>
            </div>
        </main>
    )
}